name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"

    env:
      LOG_LEVEL: DEBUG
      AGENT__GEMINI_MODEL: "gemini-2.0-flash"
      AGENT__GEMINI_API_KEY: ${{ secrets.AGENT__GEMINI_API_KEY }}
      AGENT__OPENROUTER_API_KEY: ${{ secrets.AGENT__OPENROUTER_API_KEY }}
      ECOSYSTEM__WEB3_PROVIDER_URL: "https://stylish-light-theorem.flare-mainnet.quiknode.pro/ext/bc/C/rpc"
      ECOSYSTEM__BLOCK_EXPLORER_URL: "https://flare-explorer.flare.network/api"
      VECTOR_DB__QDRANT_URL: "http://localhost:6333"
      VECTOR_DB__QDRANT_API_KEY: "your_secret_qdrant_api_key"
      GRAPH_DB__NEO4J_URI: ""
      GRAPH_DB__NEO4J_DATABASE: ""
      SOCIAL__X_API_KEY: "your_secret_twitter_key"
      SOCIAL__X_API_KEY_SECRET: "your_secret_twitter_key"
      SOCIAL__X_ACCESS_TOKEN: "your_secret_twitter_key"
      SOCIAL__X_ACCESS_TOKEN_SECRET: "your_secret_twitter_key"
      SOCIAL__TELEGRAM_API_TOKEN: "your_secret_telegram_token"
      TEE__SIMULATE_ATTESTATION_TOKEN: true
      INGESTION__CHUNK_SIZE: 5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Set up Python environment
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      # Install dependencies
      - name: Install dependencies
        run: uv sync --frozen --all-extras

      # Run unit tests with pytest
      - name: Run unit tests
        run: uv run pytest tests/unit -v

      # Run integration tests with pytest
      - name: Run integration tests
        run: uv run pytest tests/integration -v
